### ISSUE TITLE
Liberty test failing on Circle CI: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by Karm** [eclipse/microprofile-starter#310]
Current master fails on Circle CI with the undermentioned exception. Mind that the test scans logs for ERRORs. It used to work just fine.

Given the fact I don't think there were any pertinent Liberty changes, I suspect that [this is turning out to be problematic](https://github.com/eclipse/microprofile-starter/blob/master/src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/server/LibertyServer.java#L90) after all:

```
        String openLibertyVersion = "[19.0.0.9,)";
```

IMHO if you have a clean box (which the Circle CI does), there is something wrong with the version Maven downloads.

On my laptop, when I fired the liberty test as 
```
$ mvn clean verify -Pthorntail -Dtest='TestMatrixTest#liberty*' -Dskip.integration.tests=false -DSTARTER_TS_WORKSPACE=/dev/shm/
```
, it passed...

## Circle CI: All Liberty tests fail

```
circleci@default-66f7f6f4-247f-48b6-bb18-cf36079b673e:~/project$ cat target/archived-logs/org.eclipse.microprofile.starter.TestMatrixTest/libertyAll/service-a-run.log 
Extracting files to /home/circleci/wlpExtract/liberty_864148833080/wlp
Successfully extracted all product files.
Launching liberty (Open Liberty 20.0.0.6/wlp-1.0.41.cl200620200528-0414) on OpenJDK 64-Bit Server VM, version 11.0.4+11 (en_US)
[AUDIT   ] CWWKE0001I: The server liberty has been launched.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.ibm.ws.util.ThreadContextAccessor (file:/home/circleci/wlpExtract/liberty_864148833080/wlp/lib/com.ibm.ws.container.service_1.0.41.jar) to field java.lang.Thread.contextClassLoader
WARNING: Please consider reporting this to the maintainers of com.ibm.ws.util.ThreadContextAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWPKI0803A: SSL certificate created in 3.490 seconds. SSL key file: /home/circleci/wlpExtract/liberty_864148833080/wlp/usr/servers/liberty/resources/security/public.jks
[AUDIT   ] CWWKS4104A: LTPA keys created in 4.455 seconds. LTPA key file: /home/circleci/wlpExtract/liberty_864148833080/wlp/usr/servers/liberty/resources/security/ltpa.keys
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/jwt/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/ibm/api/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/metrics/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/openapi/ui/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/health/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/openapi/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/
[AUDIT   ] CWWKZ0001I: Application liberty started in 11.544 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-2.0, cdi-2.0, concurrent-1.0, distributedMap-1.0, jaxrs-2.1, jaxrsClient-2.1, jndi-1.0, json-1.0, jsonb-1.0, jsonp-1.1, jwt-1.0, microProfile-3.3, monitor-1.0, mpConfig-1.4, mpFaultTolerance-2.1, mpHealth-2.2, mpJwt-1.1, mpMetrics-2.3, mpOpenAPI-1.1, mpOpenTracing-1.3, mpRestClient-1.4, opentracing-1.3, servlet-4.0, ssl-1.0].
[AUDIT   ] CWWKF0011I: The liberty server is ready to run a smarter planet. The liberty server started in 31.227 seconds.
[err] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[err] SLF4J: Defaulting to no-operation (NOP) logger implementation
[err] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[AUDIT   ] CWWKE0085I: The server liberty is stopping because the JVM is exiting.
[AUDIT   ] quiesce.begin
[err] 
!ENTRY org.eclipse.osgi 4 0 2020-06-16 12:53:21.631
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.lang.IllegalArgumentException: org.eclipse.osgi
	at com.ibm.ws.artifact.url.internal.NotABundleResourceURLConnection.getManifestKeyForBundle(NotABundleResourceURLConnection.java:51)
	at com.ibm.ws.artifact.url.internal.NotABundleResourceURLConnection.forgetBundle(NotABundleResourceURLConnection.java:96)
	at com.ibm.ws.artifact.url.internal.URLStreamHandlerServiceImpl.addingBundle(URLStreamHandlerServiceImpl.java:56)
	at com.ibm.ws.artifact.url.internal.URLStreamHandlerServiceImpl.addingBundle(URLStreamHandlerServiceImpl.java:29)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:235)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:141)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:133)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:498)
	at org.eclipse.osgi.container.Module.doStop(Module.java:656)
	at org.eclipse.osgi.container.Module.stop(Module.java:520)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:220)
	at java.base/java.lang.Thread.run(Thread.java:834)
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/
[AUDIT   ] CWWKZ0009I: The application liberty has stopped successfully.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/metrics/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/health/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/openapi/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/openapi/ui/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/jwt/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/ibm/api/
[AUDIT   ] CWWKE0036I: The server liberty stopped after 38.654 seconds.

```

**Comment by Emily-Jiang** [comment]
What is the difference between your local environment and the circleCI? Why does it need to load slf4j class? Did you add the log recently? The logger needs to be mentioned as a dependency, not provided by runtime though as Liberty does not automatically package it.

**Comment by Karm** [comment]
@Emily-Jiang 

 > What is the difference between your local environment and the circleCI? 
Circle CI starts with a clean slate. My local box has a tun of various files Liberty creates plus downlaoded artifacts...

> Why does it need to load slf4j class?
No idea. It used to work.

> Did you add the log recently? 
No.

I think it's just that some Liberty update broke it and we don't know which since there is a version range in the pom instead of an explicit version.

What happens if you try it locally?

**Comment by Emily-Jiang** [comment]
> I think it's just that some Liberty update broke it and we don't know which since there is a version range in the pom instead of an explicit version.

What happens if you try it locally?

The version range was in place many months ago.

**Comment by Karm** [comment]
@Emily-Jiang 

> The version range was in place many months ago.

Well...and hasn't there been any Liberty updates the range would pick up?

**Comment by Emily-Jiang** [comment]
@Karm I tried to replicate this but I got this error:
```
Caused by: java.io.FileNotFoundException: ~/temp/liberty-unzip.log (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:292)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:229)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)

```
What else do I need to before running the command 
`$ mvn clean verify -Pthorntail -Dtest='TestMatrixTest#liberty*' -Dskip.integration.tests=false -DSTARTER_TS_WORKSPACE=~/temp`

**Comment by Karm** [comment]
@Emily-Jiang Resolved on the call, the culprit was the mysterious not-expanded `~/temp`. No idea why though. #NotAMacUser

**Comment by Emily-Jiang** [comment]
Thank you @Karm ! As commented on gitter, I can't replicate this locally despite of using a brand new .m2 repo.

**Comment by Karm** [comment]
We will disable Liberty on Circle CI.
