### ISSUE TITLE
Liberty random fails are caused by it using an interval [19.0.0.9,)

### ISSUE THREAD

**Issue by Karm** [eclipse/microprofile-starter#328]
Hello, the mysterious error messagethe CI is catching is this one: `!MESSAGE FrameworkEvent ERROR` (full log below).

We are chasing ghosts. I can reproduce it locally too now. The reason is that *in the meantime* between the last locally run trial and the CI failing again, there was a new Liberty release which broke it.

I don't think we should be burning time chasing ghosts on Starter as its main purpose is not being a QA for involved runtimes and I would like this [line](https://github.com/eclipse/microprofile-starter/blob/master/src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/server/LibertyServer.java#L90):

```
90         String openLibertyVersion = "[19.0.0.9,)";
```

to be set to a fixed version instead of an interval. *Some* unknown version of Liberty worked just fine in Starter and now the currently chosen one `Open Liberty 20.0.0.8/wlp-1.0.43.cl200820200721-1900` fails.

I welcome your thoughts and feedback, @Emily-Jiang , @rdebusscher 

K.

```
$ cat  target/archived-logs/org.eclipse.microprofile.starter.TestMatrixTest/libertyAll/service-a-run.log
Extracting files to /home/karm/wlpExtract/liberty_187380903576968/wlp
Successfully extracted all product files.
Launching liberty (Open Liberty 20.0.0.8/wlp-1.0.43.cl200820200721-1900) on OpenJDK 64-Bit Server VM, version 11.0.8+10 (en_US)
[AUDIT   ] CWWKE0001I: The server liberty has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKS4104A: LTPA keys created in 0.591 seconds. LTPA key file: /home/karm/wlpExtract/liberty_187380903576968/wlp/usr/servers/liberty/resources/security/ltpa.keys
[AUDIT   ] CWPKI0803A: SSL certificate created in 1.426 seconds. SSL key file: /home/karm/wlpExtract/liberty_187380903576968/wlp/usr/servers/liberty/resources/security/public.jks
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/openapi/ui/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/ibm/api/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/health/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/metrics/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/jwt/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/openapi/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/
[AUDIT   ] CWWKZ0001I: Application liberty started in 5.681 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-2.0, cdi-2.0, concurrent-1.0, distributedMap-1.0, jaxrs-2.1, jaxrsClient-2.1, jndi-1.0, json-1.0, jsonb-1.0, jsonp-1.1, jwt-1.0, microProfile-3.3, monitor-1.0, mpConfig-1.4, mpFaultTolerance-2.1, mpHealth-2.2, mpJwt-1.1, mpMetrics-2.3, mpOpenAPI-1.1, mpOpenTracing-1.3, mpRestClient-1.4, opentracing-1.3, servlet-4.0, ssl-1.0].
[AUDIT   ] CWWKF0011I: The liberty server is ready to run a smarter planet. The liberty server started in 13.134 seconds.
[AUDIT   ] CWWKE0085I: The server liberty is stopping because the JVM is exiting.
[err] !SESSION 2020-08-20 15:34:52.885 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.8
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US

!ENTRY org.eclipse.osgi 4 0 2020-08-20 15:34:52.887
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.io.IOException: Exception in opening zip file: /home/karm/wlpExtract/liberty_187380903576968/wlp/lib/org.eclipse.osgi_3.15.0.jar
        at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:340)
        at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.doOpen(ZipBundleFile.java:48)
        at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.open(CloseableBundleFile.java:128)
        at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.lockOpen(CloseableBundleFile.java:77)
        at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.getEntry(CloseableBundleFile.java:261)
        at org.eclipse.osgi.storage.BundleInfo$Generation.getEntry(BundleInfo.java:397)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.getEntry(EquinoxBundle.java:701)
        at com.ibm.ws.artifact.url.internal.NotABundleResourceURLConnection.getManifestKeyForBundle(NotABundleResourceURLConnection.java:48)
        at com.ibm.ws.artifact.url.internal.NotABundleResourceURLConnection.forgetBundle(NotABundleResourceURLConnection.java:96)
        at com.ibm.ws.artifact.url.internal.URLStreamHandlerServiceImpl.addingBundle(URLStreamHandlerServiceImpl.java:56)
        at com.ibm.ws.artifact.url.internal.URLStreamHandlerServiceImpl.addingBundle(URLStreamHandlerServiceImpl.java:29)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:235)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:141)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:133)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:498)
        at org.eclipse.osgi.container.Module.doStop(Module.java:656)
        at org.eclipse.osgi.container.Module.stop(Module.java:520)
        at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:220)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.NoSuchFileException: /home/karm/wlpExtract/liberty_187380903576968/wlp/lib/org.eclipse.osgi_3.15.0.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
        at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:322)
        ... 28 more
[AUDIT   ] quiesce.begin
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/
[ERROR   ] cls.class.file.not.readable 
                                                                                                               io.jaegertracing.internal.reporters.RemoteReporter$CloseCommand
                                                                                                               io/jaegertracing/internal/reporters/RemoteReporter$CloseCommand.class
[AUDIT   ] CWWKZ0009I: The application liberty has stopped successfully.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/metrics/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/health/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/openapi/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/openapi/ui/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/jwt/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/ibm/api/
[AUDIT   ] CWWKE0036I: The server liberty stopped after 18.026 seconds.
```

**Comment by Karm** [comment]
Keeps happening on Circle CI. Works on Github Workflows and locally these days.  We disable Liberty on Circle CI.
